/** \brief Can_GeneralTypes.h
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) Copyright Spansion LLC, All Rights Reserved 2014-2015
 **
 ** ALL RIGHTS RESERVED. No part of this publication may be copied and provided
 ** to any third party in any form or by any means, unless expressly agreed to
 ** in written form by Spansion. All trademarks used in this document are the
 ** property of their respective owners.
 **
 ** For further provisions please refer to the respective License Agreement.
 */

#ifndef CAN_GENERALTYPES_H
#define CAN_GENERALTYPES_H

/*==================[inclusions]============================================*/

#include <Std_Types.h>
#include <CclStack_Types.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/


/** \brief enum CanXcvr_XcvrModeType
 **
 ** Operating modes of the CAN Transceiver Driver.
 */
typedef enum canxcvr_xcvrmodetype_enum
{
  CANXCVR_TRCVMODE_NORMAL = 0,
  CANXCVR_TRCVMODE_SLEEP,
  CANXCVR_TRCVMODE_STANDBY
} CanXcvr_XcvrModeType;

/** \brief enum CanXcvr_XcvrWakeupReasonType
 **
 ** This type denotes the wake up reason detected by the CAN transceiver in detail.
 */
typedef enum canxcvr_xcvrwakeupreasontype_enum
{
  CANXCVR_WU_BY_BUS,
  CANXCVR_WU_BY_PIN,
  CANXCVR_WU_ERROR,
  CANXCVR_WU_INTERNALLY,
  CANXCVR_WU_NOT_SUPPORTED,
  CANXCVR_WU_POWER_ON,
  CANXCVR_WU_RESET,
  CANXCVR_WU_BY_SYSERR
} CanXcvr_XcvrWakeupReasonType;

/** \brief enum CanXcvr_XcvrWakeupModeType
 **
 ** This type shall be used to control the CAN transceiver concerning wake up
 ** events and wake up notifications.
 */
typedef enum canxcvr_xcvrwakeupmodetype_enum
{
  CANXCVR_WUMODE_CLEAR,
  CANXCVR_WUMODE_DISABLE,
  CANXCVR_WUMODE_ENABLE
} CanXcvr_XcvrWakeupModeType;


/****************************HISTORY*****************************************/
/****************************************************************************
Date              : 11/21/2016
By                : cmurali1
Change Description: Migrated to BAIC requirements
*****************************************************************************/

#endif /**defined(CAN_GENERALTYPES_H_INCLUDED)*/
