
#ifndef COMPILER_H
#define COMPILER_H

/** \brief Compiler abstraction header
 **
 ** This file contains compiler specific declarations for the
 ** platform using the compiler GHS for ARM architectures
 **
 ** See "Specification of Compiler Abstraction"
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) Copyright Spansion LLC, All Rights Reserved 2014-2015
 **
 ** ALL RIGHTS RESERVED. No part of this publication may be copied and provided
 ** to any third party in any form or by any means, unless expressly agreed to
 ** in written form by Spansion. All trademarks used in this document are the
 ** property of their respective owners.
 **
 ** For further provisions please refer to the respective License Agreement.
*/


/*==================[inclusions]=============================================*/

#include <Compiler_Cfg_Comm.h> /* module specific memory and pointer classes */

/*==================[macros]=================================================*/

/*------------------[Compiler vendor identification]-----------------*/

#if (defined COMPILER_VENDOR_ID) /* to prevent double definition */
#error COMPILER_VENDOR_ID already defined
#endif /* if (defined COMPILER_VENDOR_ID) */

/** \brief Vendor ID of the dedicated implementation of this module */
#define COMPILER_VENDOR_ID 66U /* Spansion */

/*------------------[compiler symbol]----------------------------------------*/

#if (defined _GREENHILLS_C_S6J3_) /* to prevent double definition */
#error _GREENHILLS_C_S6J3_ already defined
#endif /* if (defined _GREENHILLS_C_S6J3_) */

/** \brief compiler symbol for GHS Compiler for S6J3 */
#define _GREENHILLS_C_S6J3_ 1U /* PRQA S 602 */ /* Naming convention is required by AUTOSAR specification */

/*------------------[storage classes]----------------------------------------*/

#if (defined AUTOMATIC) /* to prevent double definition */
#error AUTOMATIC already defined
#endif /* if (defined AUTOMATIC) */

/** \brief definition of an automatic memory class
 **
 ** To be used for local non static variables */
#define AUTOMATIC

#if (defined STATIC) /* to prevent double definition */
#error STATIC already defined
#endif /* if (defined STATIC) */

/** \brief abstraction of compiler keyword 'static
 **
 ** values: 'static' or empty */
#define STATIC static

#if (defined INLINE) /* to prevent double definition */
#error INLINE already defined
#endif /* if (defined INLINE) */

/** \brief abstraction of compiler keyword 'inline'
 **
 ** values: 'inline' or empty */
#define INLINE

#if (defined LOCAL_INLINE) /* to prevent double definition */
#error LOCAL_INLINE already defined
#endif /* if (defined LOCAL_INLINE) */

/** \brief Definition of an inline keyword with "static" scope */
#define LOCAL_INLINE

#if (defined TYPEDEF) /* to prevent double definition */
#error TYPEDEF already defined
#endif /* if (defined TYPEDEF) */

/** \brief definition of TYPEDEF
 **
 ** values: empty */
#define TYPEDEF

#if (defined NEAR) /* to prevent double definition */
#error NEAR already defined
#endif /* if (defined NEAR) */

/** \brief definition of an near memory class
 **
 ** To be used for near addresses */
#define NEAR

#if (defined FAR) /* to prevent double definition */
#error FAR already defined
#endif /* if (defined FAR) */

/** \brief definition of an far memory class
 **
 ** To be used for far addresses */
#define FAR

/*------------------[null pointer constant]----------------------------------*/

#if (defined NULL_PTR) /* to prevent double definition */
#error NULL_PTR already defined
#endif /* if (defined NULL_PTR) */

/** \brief abstraction of the null pointer constant */
#define NULL_PTR ((P2VAR(void, AUTOMATIC, BASE_DATA)) 0)

/*------------------[macros for functions]-----------------------------------*/

#if (defined FUNC) /* to prevent double definition */
#error FUNC already defined
#endif /* if (defined FUNC) */

/** \brief abstraction for function declaration and definition
 **
 ** This macro abstracts the declaration and definition of functions
 ** and ensures the correct syntax of function declaration as
 ** required by the specific compiler.
 **
 ** \param[in] rettype return type of the function
 ** \param[in] memclass classification of the function itself */
/* MISRA-1 */ /* PRQA S 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */
#define FUNC(rettype, memclass) memclass rettype


#if (defined ISR_NATIVE) /* to prevent double definition */
#error ISR_NATIVE already defined
#endif /* if (defined ISR_NATIVE) */

#define ISR_NATIVE(x)     __interrupt void  x(void) /* MISRA-1 */ /* PRQA S 3453 */ /* macros used like functions. */
#if (defined FUNC_P2CONST) /* to prevent double definition */
#error FUNC_P2CONST already defined
#endif /* if (defined FUNC_P2CONST) */

/** \brief abstraction for function declaration and definition
 **
 ** This macro abstracts the declaration and definition of functions
 ** and ensures the correct syntax of function declaration as
 ** required by the specific compiler.
 **
 ** \param[in] rettype return type of the function
 ** \param[in] ptrclass classification of the pointer distance
 ** \param[in] memclass classification of the function itself */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define FUNC_P2CONST(rettype, ptrclass, memclass) const ptrclass rettype * memclass

#if (defined FUNC_P2VAR) /* to prevent double definition */
#error FUNC_P2VAR already defined
#endif /* if (defined FUNC_P2VAR) */

/** \brief abstraction for function declaration and definition
 **
 ** This macro abstracts the declaration and definition of functions a pointer
 ** to a variable and ensures the correct syntax of function declaration as
 ** required by the specific compiler.
 **
 ** \param[in] rettype return type of the function
 ** \param[in] ptrclass defines the classification of the pointer's distance
 ** \param[in] memclass classification of the function itself */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define FUNC_P2VAR(rettype, ptrclass, memclass) ptrclass rettype * memclass

/*------------------[macros for pointers]------------------------------------*/

#if (defined P2VAR) /* to prevent double definition */
#error P2VAR already defined
#endif /* if (defined P2VAR) */

/** \brief abstraction for pointers in RAM pointing to RAM
 **
 ** This macro abstracts the declaration and definition of pointers
 ** in RAM pointing to variables in RAM.
 **
 ** The pointer itself is modifiable.
 ** The pointer's target is modifiable.
 **
 ** \param[in] ptrtype type of the referenced variable
 ** \param[in] memclass classification of the pointer's variable itself
 ** \param[in] defines the classification of the pointer's distance */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define P2VAR(ptrtype, memclass, ptrclass) ptrclass ptrtype * memclass

#if (defined P2CONST) /* to prevent double definition */
#error P2CONST already defined
#endif /* if (defined P2CONST) */

/** \brief abstraction for pointers in RAM pointing to ROM
 **
 ** This macro abstracts the declaration and definition of pointers
 ** in RAM pointing to constants in ROM.
 **
 ** The pointer itself is modifiable.
 ** The pointer's target is not modifiable (read only).
 **
 ** \param[in] ptrtype type of the referenced constant
 ** \param[in] memclass classification of the pointer's variable itself
 ** \param[in] defines the classification of the pointer's distance */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define P2CONST(ptrtype, memclass, ptrclass) const ptrtype ptrclass * memclass

#if (defined CONSTP2VAR) /* to prevent double definition */
#error CONSTP2VAR already defined
#endif /* if (defined CONSTP2VAR) */

/** \brief abstraction for pointers in ROM pointing to RAM
 **
 ** This macro abstracts the declaration and definition of pointers
 ** in ROM pointing to variables in RAM.
 **
 ** The pointer is not modifiable. (read only).
 ** The pointer's target is modifiable.
 **
 ** \param[in] ptrtype type of the referenced variable
 ** \param[in] memclass classification of the pointer's variable itself
 ** \param[in] defines the classification of the pointer's distance */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define CONSTP2VAR(ptrtype, memclass, ptrclass) ptrclass ptrtype * const memclass

#if (defined CONSTP2CONST) /* to prevent double definition */
#error CONSTP2CONST already defined
#endif /* if (defined CONSTP2CONST) */

/** \brief abstraction for pointers in ROM pointing to ROM
 **
 ** This macro abstracts the declaration and definition of pointers
 ** in ROM pointing to constants in ROM.
 **
 ** The pointer itself is not modifiable (read only).
 ** The pointer's target is not modifiable (read only).
 **
 ** \param[in] ptrtype type of the referenced constant
 ** \param[in] memclass classification of the pointer's variable itself
 ** \param[in] defines the classification of the pointer's distance */
/* MISRA-1 */ /* PRQA S 3409, 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define CONSTP2CONST(ptrtype, memclass, ptrclass) const ptrclass ptrtype * const memclass

#if (defined P2FUNC) /* to prevent double definition */
#error P2FUNC already defined
#endif /* if (defined P2FUNC) */

/** \brief abstraction for declaration and definition of function pointers
 **
 ** This macro abstracts the declaration and definition of pointers
 ** to functions.
 **
 ** \param[in] rettype return type of the function
 ** \param[in] ptrclass defines the classification of the pointer's distance
 ** \param[in] function name respectively name of the defined type
 ** */
/* MISRA-1 */ /* PRQA S 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define P2FUNC(rettype, ptrclass, fctname) rettype ptrclass (* fctname)

/*------------------[keywords for constants]---------------------------------*/

#if (defined CONST) /* to prevent double definition */
#error CONST already defined
#endif /* if (defined CONST) */

/** \brief abstraction for declaration and definition of constants
 **
 ** This macro abstracts the declaration and definition of constants.
 **
 ** \param[in] consttype type of the constant
 ** \param[in] memclass classification of the constant itself */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define CONST(consttype, memclass) memclass const consttype

/*------------------[keywords for variables]---------------------------------*/

#if (defined VAR) /* to prevent double definition */
#error VAR already defined
#endif /* if (defined VAR) */

/** \brief abstraction for the declaration and definition of variables
 **
 ** This macro abstracts the declaration and definition of variables.
 **
 ** \param[in] vartype type of the variable
 ** \param[in] memclass classification of the variable itself */
 /* MISRA-1 */ /* PRQA S 3410 2 */
/* MISRA-1 */ /* PRQA S 3453 1 */ /* macros used like functions. */ 
#define VAR(vartype, memclass) memclass vartype

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

/****************************HISTORY*****************************************/
/****************************************************************************
Date              : 11/21/2016
By                : cmurali1
Change Description: Migrated to BAIC requirements
*****************************************************************************/

#endif /* ifndef COMPILER_H */
