
#ifndef CCLSTACK_CFG_H
#define CCLSTACK_CFG_H

/** \brief Communication Stack Config header
 **
 ** This file contains the implementation of the Communication Stack Config header
 ** 
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) Copyright Spansion LLC, All Rights Reserved 2014-2015
 **
 ** ALL RIGHTS RESERVED. No part of this publication may be copied and provided
 ** to any third party in any form or by any means, unless expressly agreed to
 ** in written form by Spansion. All trademarks used in this document are the
 ** property of their respective owners.
 **
 ** For further provisions please refer to the respective License Agreement.
*/

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/* this type can be configured:
 * - uint16
 * - range: 0 .. PduIdmax */
/** \brief type for a unique identifier for a PDU */
typedef uint16 PduIdType;

/* this type can be configured:
 * - uint32
 * - range: 0 .. PduLengthmax
 */
/** \brief type for lengths information of a PDU */
typedef uint32 PduLengthType;

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

/****************************HISTORY*****************************************/
/****************************************************************************
Date              : 11/21/2016
By                : cmurali1
Change Description: Migrated to BAIC requirements
*****************************************************************************/

#endif /* ifndef CCLSTACK_CFG_H */

